minimap_wrapper <- function(query_fa, target_genome, out) {
  system2("minimap2", args = c("-ax", "splice", target_genome, query_fa), stdout = out)
}

sam_to_bam_wrapper <- function(sam_file, bam_file) {
  system2("samtools", args = c("view", "-b", "-o", bam_file, sam_file))
}

#' Use external minimap2 to find homolog in another genome.
#'
#' @param target target genome FASTA file path.
#' @param query query sequence. Either a path to a FASTA file or a [Biostrings::DNAStringSet()] object..
#' @param chromosome,start,end position of segment in query sequence. Optional, leave blank to search the entire query sequence.
#'
#' @export
setGeneric("minimap_homolog",
  function(target, query, chromosome, start, end) {
    standardGeneric("minimap_homolog")
  }
)

setMethod("minimap_homolog",
  signature(
    target = "character",
    query = "character",
    chromosome = "missing",
    start = "missing",
    end = "missing"
  ),
  function(target, query) {

    # 1. set up some tmp files.
    tmp_files <- list(
      sam = tempfile(fileext = ".sam"),
      bam = tempfile(fileext = ".bam")
    )

    # 2. minimap to target_genome.
    minimap_wrapper(query, target, tmp_files$sam)
    sam_to_bam_wrapper(tmp_files$sam, tmp_files$bam)
    aln <- GenomicAlignments::readGAlignments(tmp_files$bam)

    # 3. clean tmp files.
    lapply(tmp_files, unlink)

    return(aln)
  }
)

setMethod("minimap_homolog",
  signature(
    target = "character",
    query = "DNAStringSet",
    chromosome = "missing",
    start = "missing",
    end = "missing"
  ),
  function(target, query) {
    tmp_fasta <- tempfile(fileext = ".fasta")
    Biostrings::writeXStringSet(query, tmp_fasta)
    homolog_dna <- minimap_homolog(target, tmp_fasta)
    unlink(tmp_fasta)
    return(homolog_dna)
  }
)


setMethod("minimap_homolog",
  signature(
    target = "character",
    query = "character",
    chromosome = "character",
    start = "numeric",
    end = "numeric"
  ),
  function(target, query, chromosome, start, end) {
    tmp_fasta <- tempfile(fileext = ".fasta")
    gr <- GenomicRanges::GRanges(seqnames = chromosome, IRanges::IRanges(start, end))
    Biostrings::readDNAStringSet(query)[gr] |>
      Biostrings::writeXStringSet(tmp_fasta)
    homolog_dna <- minimap_homolog(target, tmp_fasta)
    unlink(tmp_fasta)
    return(homolog_dna)
  }
)


#' Fetch target sequence from target genome by alignment.
#'
#' @param aln alignment object generated by [panlabr::minimap_homolog()].
#' @param target_genome target genome FASTA path.
#'
#' @export
aln_to_dna <- function(aln, target_genome) {
  target_gr <- GenomicRanges::GRanges(aln)
  homolog_dna <- Biostrings::readDNAStringSet(target_genome)[target_gr] |>
    setNames(paste(as.character(target_gr), aln@cigar, sep = ":"))
  return(homolog_dna)
}


#' Generate genbank string from target genome by alignment.
#'
#' @param aln alignment object generated by [panlabr::minimap_homolog()].
#' @param target_genome target genome FASTA path.
#' @param target_gtf target genome annotation GTF path.
#'
#' @export
aln_to_genbank <- function(aln, target_genome, target_gtf) {

  if (length(aln) != 1) {
    stop("Length of aln can only be 1.")
  }

  chromosome <- GenomicRanges::seqnames(aln) |> as.character()
  start <- GenomicRanges::start(aln)
  end <- GenomicRanges::end(aln)

  return(make_genbank_string(target_genome, target_gtf, chromosome, start, end))
}
